inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - ./cops/deep_freeze.rb
  - ./cops/unscoped_find.rb

AllCops:
  TargetRubyVersion: 2.7
  DisabledByDefault: true # Only turn stuff on when we're ready
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/old_migrations/**/*'
    - 'tmp/**/*'

# Does not yet exist?
# Layout/BeginEndAlignment:
#   Enabled: true

# Use this for now
Layout/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: start_of_line

Layout/ClassStructure:
  Enabled: true

Layout/DotPosition:
  Enabled: true
  Exclude:
    - 'db/**/*' # generated automatically

Layout/EmptyLineAfterGuardClause:
  Enabled: true

Layout/EmptyLinesAroundAccessModifier:
  Enabled: true

Layout/IndentationConsistency:
  Enabled: true

Layout/IndentationStyle:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true

Layout/SpaceBeforeBlockBraces:
  Enabled: true

Layout/SpaceInsideBlockBraces:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  Exclude:
    - 'db/**/*' # generated automatically

Layout/TrailingEmptyLines:
  Enabled: true
  EnforcedStyle: final_newline

Layout/TrailingWhitespace:
  Enabled: true

Lint:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true

Security:
  Enabled: true

Security/YAMLLoad:
  Enabled: true
  Exclude:
    - 'db/data_scripts/update_fixtures_from_db.rb' # safe_yaml doesn't like our structure fixture timestamps

CDD/DeepFreeze:
  Enabled: true
  Exclude:
    - 'app/extensions/**/*'
    - 'config/**/*'
    - 'lib/**/*'
    - 'script/**/*'
    - 'spec/**/*'
    - 'test/**/*'

CDD/UnscopedFind:
  Enabled: true
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'spec/**/*'
    - 'test/**/*'
  Ignore:
    - 'find_or_build'

Style/MutableConstant:
  Enabled: true

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19_no_mixed_keys
  Exclude:
    - 'db/**/*' # The hairtrigger gem currently uses the old syntax

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  Exclude:
    - 'db/**/*'
    - 'bin'

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: percent

Style/WordArray:
  Enabled: true
  EnforcedStyle: percent
  Exclude:
    - 'db/schema.rb'

Layout/LineLength:
  Enabled: true
  Max: 130

Performance:
  Enabled: true
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Rails:
  DisabledByDefault: true # Only turn stuff on when we're ready

Rails/SafeNavigation:
  Enabled: true
  ConvertTry: true

Rails/DynamicFindBy:
  Enabled: true
  Whitelist:
    - 'find_by_sql'                                                      # defined by rails and app/models/batch_field.rb, app/models/searching/searched_readout.rb
    - 'find_by_ids'                                                      # defined in app/mixins/habtm_collection_set.rb
    - 'find_by_session_id'                                               # defined in config/initializers/faster_session.rb
    - 'find_by_synonym_and_data_set'                                     # defined in app/models/private_molecule.rb
    - 'find_by_synonym_and_project'                                      # defined in app/models/private_molecule.rb
    - 'find_by_public_access_registration_token'                         # defined in app/models/public_snapshot.rb
    - 'find_by_structure_group_numbers_and_readout_definition_ids'       # defined in app/models/run.rb
    - 'find_by_structure_group_numbers_and_readout_definition_ids_query' # defined in app/models/run.rb
    - 'search_with_molecule_batch_identifier'                                # SpecifiedBatch

Rails/TimeZone:
  Enabled: true
  EnforcedStyle: strict
  Exclude:
    - lib/background_process.rb # Runs outside of Rails, so Time.zone is not available
    - config/deploy.rb # Runs outside of Rails, so Time.zone is not available

Rails/OutputSafety:
  Enabled: true

RSpec:
  DisabledByDefault: true # Only turn stuff on when we're ready

RSpec/Focus:
  Enabled: true

# New cops available (disabled manually)
Lint/UnreachableLoop:
  Enabled: false
Lint/EmptyConditionalBody:
  Enabled: false
Lint/TopLevelReturnWithArgument:
  Enabled: false
Lint/UselessTimes:
  Enabled: false
Lint/FloatComparison:
  Enabled: false
Lint/ConstantDefinitionInBlock:
  Enabled: false
Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Lint/UselessMethodDefinition:
  Enabled: false
Lint/AmbiguousAssignment: # (new in 1.7)
  Enabled: true
Lint/DeprecatedConstants: # (new in 1.8)
  Enabled: true
Lint/DuplicateBranch: # (new in 1.3)
  Enabled: false
Lint/DuplicateRegexpCharacterClassElement: # (new in 1.1)
  Enabled: true
Lint/EmptyBlock: # (new in 1.1)
  Enabled: false
Lint/EmptyClass: # (new in 1.3)
  Enabled: false
Lint/LambdaWithoutLiteralBlock: # (new in 1.8)
  Enabled: true
Lint/NoReturnInBeginEndBlocks: # (new in 1.2)
  Enabled: false
Lint/NumberedParameterAssignment: # (new in 1.9)
  Enabled: true
Lint/OrAssignmentToConstant: # (new in 1.9)
  Enabled: true
Lint/RedundantDirGlobSort: # (new in 1.8)
  Enabled: true
Lint/SymbolConversion: # (new in 1.9)
  Enabled: false
Lint/ToEnumArguments: # (new in 1.1)
  Enabled: false
Lint/TripleQuotes: # (new in 1.9)
  Enabled: true
Lint/UnexpectedBlockArity: # (new in 1.5)
  Enabled: false
Lint/UnmodifiedReduceAccumulator: # (new in 1.1)
  Enabled: true
